name: swap_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  pinput: ^5.0.0
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^6.0.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/login/icon.png"

flutter:
  uses-material-design: true
  assets:
    - asset/login/
    - asset/home/
    - asset/account/






