name: swap_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  pinput: ^5.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.2.2
  mobile_scanner: ^7.0.1
  flutter_launcher_icons: ^0.14.4
  equatable: ^2.0.5
  # Map
  google_maps_flutter: ^2.4.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_polyline_points: ^3.1.0
  location: ^5.0.2
  geocoding: ^2.1.0
  http: ^1.5.0
  webview_flutter: ^4.11.2 
  percent_indicator: ^4.2.3
  image_picker: ^1.0.7
  rename: ^3.1.0
  intl: ^0.19.0

  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/login/icon.png"

flutter:
  uses-material-design: true
  assets:
    - asset/login/
    - asset/home/
    - asset/account/






